$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$p2=Join-Path $root 'Phase 2 Doc';$p3=Join-Path $root 'Phase 3 Doc'
$fsRef=Join-Path $p2 'FS-PLPI BAR - B&S Batch Add Printing and Leaflet Folding.docx'
$dsRef=Join-Path $p2 'DS-PLPI BAR - B&S Batch Add Printing and Leaflet Folding - Exact Template.docx'
$ursPath=Join-Path $p3 'URS-PLPI BAR - Pre-Assembly Production Control Assembly and Post-Assembly QC.docx'
$fsOut=Join-Path $p3 'FS-PLPI BAR - Pre-Assembly Production Controller Handheld Assembly and Post-Assembly QC.docx'
$dsOut=Join-Path $p3 'DS-PLPI BAR - Pre-Assembly Production Controller Handheld Assembly and Post-Assembly QC.docx'
$shots=Join-Path $p3 'screenshots';$assemblyShots=Join-Path $root 'assembly_module_document\screenshots'

function Clean($s){(($s-replace([char]13),' '-replace([char]7),' ')-replace'\s+',' ').Trim()}
function EndR($d){$r=$d.Content;$r.Collapse(0);$r}
function Font($r,$size=9,$bold=$false,$colour=0){$r.Font.Name='Verdana';$r.Font.Size=$size;$r.Font.Bold=if($bold){1}else{0};$r.Font.Color=$colour}
function P($d,$text='',$bold=$false,$size=9,$after=5){$p=$d.Paragraphs.Add((EndR $d));$p.Range.Text=$text;Font $p.Range $size $bold 0;$p.Range.ParagraphFormat.SpaceAfter=$after;$p.Range.InsertParagraphAfter()|Out-Null;$p}
function H($d,$text,$level){$p=P $d $text $true $(if($level-eq1){14}elseif($level-eq2){11}else{9}) 5;try{$p.Range.Style="Heading $level"}catch{};$p.Range.Font.Name='Verdana';$p.Range.Font.Color=8210719;$p.Range.Font.Bold=1;$p.Range.ParagraphFormat.KeepWithNext=-1;$p}
function Label($d,$name,$text){$p=P $d '' $false 9 4;$p.Range.Text='';$a=$p.Range.Duplicate;$a.Text="${name}: ";Font $a 9 $true 0;$b=$d.Range($a.End,$a.End);$b.Text=$text;Font $b 9 $false 0;$p.Range.InsertParagraphAfter()|Out-Null}
function Img($d,$path,$caption,$width=430){if(!(Test-Path -LiteralPath $path)){throw"Missing $path"};$r=EndR $d;$i=$d.InlineShapes.AddPicture($path,$false,$true,$r);$i.LockAspectRatio=-1;$i.Width=$width;$i.Range.Paragraphs(1).Alignment=1;$i.Range.InsertParagraphAfter()|Out-Null;$p=P $d $caption $false 8 6;$p.Alignment=1;$p.Range.Font.Italic=1}
function Stories($d,$ot,$nt,$oi,$ni){foreach($s in $d.Sections){foreach($k in 1,2,3){foreach($r in @($s.Headers.Item($k).Range,$s.Footers.Item($k).Range)){try{$r.Find.Execute($ot,$false,$false,$false,$false,$false,$true,1,$false,$nt,2)|Out-Null}catch{};try{$r.Find.Execute($oi,$false,$false,$false,$false,$false,$true,1,$false,$ni,2)|Out-Null}catch{}}}}}
function Start($w,$ref,$out,$keep,$ot,$nt,$oi,$ni){Copy-Item -LiteralPath $ref -Destination $out -Force;$d=$w.Documents.Open($out,$false,$false);try{$d.TrackRevisions=$false}catch{};$w.Options.Pagination=$false;$d.Repaginate();$s=$d.GoTo(1,1,($keep+1)).Start;$e=$d.Content.End-1;if($e-gt$s){$d.Range($s,$e).Delete()|Out-Null};Stories $d $ot $nt $oi $ni;$d}

$module=@{
'1'=@{Title='Pre-Assembly QC Module';Purpose='Verify the eligible batch, printed materials and product sample; make the approved assembly mock-up available; record applicable counts; and sign the batch for Production Control.';Role='Authorised Pre-Assembly QC user';Flow='Search the eligible Stage 9 queue, open a batch, review its read-only product and route context, complete line clearance and each applicable label, sample, leaflet, braille, carton and route-specific check, record specimens, leaflet folds and tamper seals, then use User Sign Off.';Rules='Only eligible batches are shown. Sign-off requires all applicable confirmations and counts, records the authenticated user, role and date/time, locks the record and releases it to Production Control.'}
'2'=@{Title='Production Controller Handheld and Room Allocation Module';Purpose='Use the authorised SeUIC handheld for STOCK TAKE OUT, Box ID verification, Line Clearance and Assembly Room allocation.';Role='Authorised Production Controller using the SeUIC handheld';Flow='Open GOODS IN and select STOCK TAKE OUT; scan or enter Stock ID; verify Product, Part No., Batch No., Goods In Boxes, Qty., Location, IMP and Contract; select TRANSFER; scan or enter Box ID; complete both Line Clearance checks; confirm a positive whole-number box count; accept or cancel any count change; select Room1 or Room2; then use CONFIRMED BY.';Rules='Blank Box ID is blocked. CONFIRMED BY is disabled until both checks, valid count, resolved count change and room selection are complete. Confirmation updates the BAR and displays BAR UPDATED with user, date/time and room. Back, Cancel or Power before confirmation does not complete the record, and a completed form does not pre-fill a later transfer.'}
'3'=@{Title='Assembly Room Module';Purpose='Execute the allocated batch through Initial Checks, Random Sample Check, IPC Checks and Reconciliation & Closure.';Role='Authorised Assembly Room user';Flow='Open an allocated active batch, confirm start, record team briefing and room attendance where applicable, complete and sign each of the four controlled pages, retain photo evidence against the relevant IPC, resolve holds or reconciliation exceptions, and complete the final hand-off.';Rules='The batch is available only in its allocated room. Each page validates mandatory data before sign-off and becomes read-only after signing. Final completion requires all four pages and completed reconciliation, records the finish user and date/time, and releases the batch to Post-Assembly QC.'}
'4'=@{Title='Post-Assembly QC Module';Purpose='Verify the finished batch, quantities, boxes and pack details; generate controlled quarantine labels; and release the signed batch to Pre-QP.';Role='Authorised Post-Assembly QC user';Flow='Open an Assembly-complete batch, review product and Assembly status, record sample packs checked, full quantity and total boxes, complete any required per-box allocation, verify pack details against the BAR, generate the required quarantine labels and use User Sign Off.';Rules='Sign-off and quarantine-label generation remain blocked while mandatory checks or quantity/box data are incomplete or inconsistent. Voids and reprints retain reason, user and date/time. Completion records the authenticated user, role, checks, quantities, comments and date/time, locks the record and releases it to Pre-QP.'}
}

$w=$null;$u=$null;$fs=$null;$ds=$null
try{
 $w=New-Object -ComObject Word.Application;$w.Visible=$false;$w.DisplayAlerts=0
 $u=$w.Documents.Open($ursPath,$false,$true);$req=@();foreach($t in $u.Tables){if($t.Columns.Count-ge2){for($r=2;$r-le$t.Rows.Count;$r++){try{$id=Clean $t.Cell($r,1).Range.Text;$tx=Clean $t.Cell($r,2).Range.Text;if($id-match'^4\.[1-4]\.\d+$'){$req+=[pscustomobject]@{Id=$id;Text=$tx;Stage=($id-split'\.')[1]}}}catch{}}}};$u.Close($false);$u=$null;if($req.Count-ne69){throw"Expected 69 requirements, got $($req.Count)"}

 $fs=Start $w $fsRef $fsOut 3 'Functional Specification: PLPI Batch Record Automation Phase 2' 'Functional Specification: PLPI Batch Record Automation Phase 3' 'PLPI/BAR/FS/01/v1' 'PLPI/BAR/FS/02/v1'
 try{$fs.Tables.Item(4).Cell(2,3).Range.Text='Functional Specification for PLPI BAR Stages 9-12: Pre-Assembly QC, Production Controller handheld and room allocation, Assembly Room and Post-Assembly QC.';$fs.Tables.Item(4).Cell(2,4).Range.Text='Sep 2026'}catch{}
 H $fs '1. Introduction' 1|Out-Null;P $fs 'PLPI Batch Record Automation Stages 9-12 extend the controlled electronic BAR workflow from Pre-Assembly QC through Production Controller handheld Line Clearance and room allocation, Assembly Room execution and Post-Assembly QC.'|Out-Null
 H $fs '1.1 Purpose of the document' 2|Out-Null;P $fs 'This Functional Specification defines the user-visible behaviour, validations, controlled actions, outputs, audit attribution and hand-offs required by the approved Stage 9-12 URS and current wireframes.'|Out-Null
 H $fs '1.2 Scope' 2|Out-Null;P $fs 'The scope is limited to the four modules below. Physical database structures, API endpoints, infrastructure and device-management mechanisms are not specified where the approved project evidence does not establish them.'|Out-Null
 H $fs '2. Overall Description' 1|Out-Null;P $fs 'The batch progresses in sequence from Stage 9 to Stage 12. Each stage is role controlled, presents only eligible work, revalidates mandatory conditions at sign-off, records authenticated attribution and makes completed records read-only before the next hand-off.'|Out-Null
 H $fs '3. Functional Specification' 1|Out-Null
 foreach($k in '1','2','3','4'){$m=$module[$k];H $fs "3.$k $($m.Title)" 2|Out-Null;Label $fs 'Priority' 'High';Label $fs 'Purpose' $m.Purpose;Label $fs 'Role' $m.Role;Label $fs 'Functional operation' $m.Flow;Label $fs 'Business rules and output' $m.Rules;H $fs "3.$k.1 Approved URS requirements implemented" 3|Out-Null;foreach($q in @($req|Where-Object { $_.Stage -eq $k })){P $fs "$($q.Id)  $($q.Text)"|Out-Null}}
 H $fs '4. Non-Functional Specification' 1|Out-Null
 foreach($x in @(@('4.1 Audit Trail','Retain authenticated user, role, batch, action, result, date/time and applicable previous/new values for controlled actions.'),@('4.2 Availability and Recoverability','A temporary device, print or service interruption shall not create false completion; committed signatures and audit events shall remain retained.'),@('4.3 Security','Access and operational sign-off shall be authenticated and role based.'),@('4.4 Error Handling and Usability','Validation shall identify the unmet condition and retain the user on the current step; desktop and handheld screens shall use clear labels, status and action gating.'),@('4.5 Testing and Training','Testing shall cover every approved URS requirement, role, positive flow, validation, cancellation, interruption, audit event and hand-off. Applicable controlled documents and training shall be approved before release.'))){H $fs $x[0] 2|Out-Null;P $fs $x[1]|Out-Null}
 $w.Options.Pagination=$true;$fs.Save();$fs.Close($false);$fs=$null

 $ds=Start $w $dsRef $dsOut 2 'Design Specification: PLPI Batch Record Automation Phase 2' 'Design Specification: PLPI Batch Record Automation Phase 3' 'PLPI/BAR/DS/01/v1' 'PLPI/BAR/DS/02/v1'
 H $ds '1. Introduction' 1|Out-Null;P $ds 'This Design Specification defines the logical screens, states, validations, audit records and stage hand-offs for PLPI BAR Stages 9-12. It uses the current URS and current wireframes and does not invent unapproved physical architecture.'|Out-Null
 H $ds '2. Overall Design' 1|Out-Null;P $ds 'Available records are restricted by role and preceding-stage completion. In-progress records retain only committed controlled events. Sign-off is enabled only after applicable gates pass. Completed records display attribution read-only and become available to the next authorised stage.'|Out-Null
 H $ds '3. Detailed Design Specification' 1|Out-Null
 H $ds '3.1 Pre-Assembly QC Module' 2|Out-Null;Img $ds (Join-Path $shots '01-pre-assembly-queue.png') 'Figure 1 - Pre-Assembly QC batch queue';Img $ds (Join-Path $shots '01-pre-assembly-detail.png') 'Figure 2 - Pre-Assembly verification and sign-off';Label $ds 'Design behaviour' $module['1'].Flow;Label $ds 'Validation and exit state' $module['1'].Rules;Label $ds 'Traceability' 'URS 4.1.1 to 4.1.12; FS 3.1.'
 H $ds '3.2 Production Controller Handheld and Room Allocation Module' 2|Out-Null;Img $ds (Join-Path $shots '02-handheld-menu.png') 'Figure 3 - SeUIC GOODS IN menu' 190;Img $ds (Join-Path $shots '02-handheld-stock-take-out.png') 'Figure 4 - STOCK TAKE OUT and TRANSFER' 190;Img $ds (Join-Path $shots '02-handheld-box-verification.png') 'Figure 5 - Box ID verification' 190;Img $ds (Join-Path $shots '02-handheld-line-clearance.png') 'Figure 6 - Line Clearance and Assembly Room allocation' 190;Label $ds 'Design behaviour' $module['2'].Flow;Label $ds 'Validation and exit state' $module['2'].Rules;Label $ds 'Traceability' 'URS 4.2.1 to 4.2.20; FS 3.2.'
 H $ds '3.3 Assembly Room Module' 2|Out-Null;foreach($f in @(@('01-assembly-batch-queue.png','Figure 7 - Assembly Room batch queue'),@('02-start-batch-confirmation.png','Figure 8 - Start batch confirmation'),@('03-initial-checks.png','Figure 9 - Initial Checks'),@('04-random-sample-check.png','Figure 10 - Random Sample Check'),@('05-ipc-checks.png','Figure 11 - IPC Checks'),@('06-reconciliation-closure.png','Figure 12 - Reconciliation and Closure'))){Img $ds (Join-Path $assemblyShots $f[0]) $f[1]};Label $ds 'Design behaviour' $module['3'].Flow;Label $ds 'Validation and exit state' $module['3'].Rules;Label $ds 'Traceability' 'URS 4.3 - 24 approved requirements; FS 3.3.'
 H $ds '3.4 Post-Assembly QC Module' 2|Out-Null;Img $ds (Join-Path $shots '04-post-assembly-queue.png') 'Figure 13 - Post-Assembly QC batch queue';Img $ds (Join-Path $shots '04-post-assembly-detail.png') 'Figure 14 - Post-Assembly QC verification and completion';Label $ds 'Design behaviour' $module['4'].Flow;Label $ds 'Validation and exit state' $module['4'].Rules;Label $ds 'Traceability' 'URS 4.4 - 13 approved requirements; FS 3.4.'
 H $ds '4. Additional Non-Functional Requirements' 1|Out-Null;P $ds 'The design shall use authenticated role access, immutable ordinary completed-state display, audit attribution, clear validation messages, recoverable committed events, controlled printing and verification against all approved URS traces.'|Out-Null
 $w.Options.Pagination=$true;$ds.Save();$ds.Close($false);$ds=$null
 'Created retained-template FS and DS.'
}
finally{if($u){try{$u.Close($false)}catch{}};if($fs){try{$fs.Close($false)}catch{}};if($ds){try{$ds.Close($false)}catch{}};if($w){try{$w.Quit()}catch{}};Get-Process WINWORD -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue}
