$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
Add-Type -AssemblyName System.Drawing

$root=Split-Path -Parent $PSScriptRoot
$phase2=Join-Path $root 'Phase 2 Doc';$phase3=Join-Path $root 'Phase 3 Doc'
$fsRef=Join-Path $phase2 'FS-PLPI BAR - B&S Batch Add Printing and Leaflet Folding.docx'
$dsRef=Join-Path $phase2 'DS-PLPI BAR - B&S Batch Add Printing and Leaflet Folding - Exact Template.docx'
$urs=Join-Path $phase3 'URS-PLPI BAR - Pre-Assembly Production Control Assembly and Post-Assembly QC.docx'
$fsOut=Join-Path $phase3 'FS-PLPI BAR - Pre-Assembly Production Controller Handheld Assembly and Post-Assembly QC.docx'
$dsOut=Join-Path $phase3 'DS-PLPI BAR - Pre-Assembly Production Controller Handheld Assembly and Post-Assembly QC.docx'
$shots=Join-Path $phase3 'screenshots';$assembly=Join-Path $root 'assembly_module_document\screenshots'
$work=Join-Path $root 'phase3_template_work\ooxml';if(Test-Path $work){Remove-Item -LiteralPath $work -Recurse -Force};New-Item -ItemType Directory -Path $work -Force|Out-Null

# Reuse only the original Phase 3 content map from the COM builder; do not execute its authoring section.
$contentSource=[IO.File]::ReadAllText((Join-Path $PSScriptRoot 'rebuild_phase3_fs_ds_phase2_template.ps1'))
$mm=[regex]::Match($contentSource,'(?s)\$modules=@\(.*?\r?\n\)\r?\n\r?\n(?:if\(\$env:PLPI_PHASE3_CONTENT_ONLY.*?\r?\n\r?\n)?\$word=')
if(-not $mm.Success){throw 'Could not load the Phase 3 module content map.'}
$moduleCode=$mm.Value -replace '(?s)\r?\n\r?\n(?:if\(\$env:PLPI_PHASE3_CONTENT_ONLY.*?\r?\n\r?\n)?\$word=.*$',''
Invoke-Expression $moduleCode

$wNs='http://schemas.openxmlformats.org/wordprocessingml/2006/main';$rNs='http://schemas.openxmlformats.org/officeDocument/2006/relationships'
$relNs='http://schemas.openxmlformats.org/package/2006/relationships';$blue='002060';$grid='B7B7B7';$script:docPr=100
function E([string]$s){if($null-eq$s){return''};return [Security.SecurityElement]::Escape($s)}
function XRun([string]$text,[int]$size=18,[bool]$bold=$false,[string]$color='002060',[bool]$italic=$false){
  $b=if($bold){'<w:b/>'}else{''};$i=if($italic){'<w:i/>'}else{''}
  return '<w:r><w:rPr><w:rFonts w:ascii="Verdana" w:hAnsi="Verdana"/>'+$b+$i+'<w:color w:val="'+$color+'"/><w:sz w:val="'+$size+'"/><w:szCs w:val="'+$size+'"/></w:rPr><w:t xml:space="preserve">'+(E $text)+'</w:t></w:r>'
}
function P([string]$text,[string]$style='Normal',[string]$align='both',[int]$size=18,[bool]$bold=$false,[int]$before=0,[int]$after=100,[bool]$italic=$false){
  $out=if($style-eq'Heading1'){0}elseif($style-eq'Heading2'){1}else{9};$keep=if($style-match'Heading'){'<w:keepNext/>'}else{''}
  return '<w:p><w:pPr><w:pStyle w:val="'+$style+'"/><w:jc w:val="'+$align+'"/><w:spacing w:before="'+$before+'" w:after="'+$after+'"/>'+$keep+'<w:outlineLvl w:val="'+$out+'"/></w:pPr>'+(XRun $text $size $bold $blue $italic)+'</w:p>'
}
function H1([string]$t){P $t 'Heading1' 'left' 28 $true 160 120}
function H2([string]$t){P $t 'Heading2' 'left' 24 $true 120 100}
function PB(){'<w:p><w:r><w:br w:type="page"/></w:r></w:p>'}
function Bullet([string]$t){'<w:p><w:pPr><w:pStyle w:val="Normal"/><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr><w:ind w:left="360" w:hanging="180"/><w:spacing w:after="60"/></w:pPr>'+(XRun $t 18 $false $blue $false)+'</w:p>'}
function Tc([string]$inner,[int]$width,[string]$fill='FFFFFF',[string]$vAlign='center'){'<w:tc><w:tcPr><w:tcW w:w="'+$width+'" w:type="dxa"/><w:shd w:fill="'+$fill+'"/><w:vAlign w:val="'+$vAlign+'"/></w:tcPr>'+$inner+'</w:tc>'}
function CellP([string]$text,[bool]$header=$false,[int]$size=16,[string]$align='left'){
  $c=if($header){'FFFFFF'}else{$blue};return '<w:p><w:pPr><w:jc w:val="'+$align+'"/><w:spacing w:after="0"/></w:pPr>'+(XRun $text $size $header $c $false)+'</w:p>'
}
function Table([string[]]$headers,[object[]]$rows,[int[]]$widths){
  $total=($widths|Measure-Object -Sum).Sum;$x='<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="'+$total+'" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblCellMar><w:top w:w="70" w:type="dxa"/><w:left w:w="90" w:type="dxa"/><w:bottom w:w="70" w:type="dxa"/><w:right w:w="90" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid>'
  foreach($w in $widths){$x+='<w:gridCol w:w="'+$w+'"/>'};$x+='</w:tblGrid><w:tr><w:trPr><w:tblHeader/></w:trPr>'
  for($i=0;$i-lt$headers.Count;$i++){$x+=Tc (CellP $headers[$i] $true 16 'center') $widths[$i] $blue};$x+='</w:tr>'
  foreach($row in $rows){$x+='<w:tr>';for($i=0;$i-lt$headers.Count;$i++){$a=if($i-eq0-and$headers.Count-gt2){'center'}else{'left'};$x+=Tc (CellP ([string]$row[$i]) $false 16 $a) $widths[$i]};$x+='</w:tr>'}
  return $x+'</w:tbl>'+(P '' 'Normal' 'left' 18 $false 0 80)
}
function ModuleTable($m){
  $w1=1560;$w2=7460;$x='<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="9020" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblCellMar><w:top w:w="70" w:type="dxa"/><w:left w:w="90" w:type="dxa"/><w:bottom w:w="70" w:type="dxa"/><w:right w:w="90" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="1560"/><w:gridCol w:w="7460"/></w:tblGrid>'
  $x+='<w:tr><w:trPr><w:tblHeader/></w:trPr><w:tc><w:tcPr><w:tcW w:w="9020" w:type="dxa"/><w:gridSpan w:val="2"/><w:shd w:fill="'+$blue+'"/></w:tcPr>'+(CellP ($m.Code+'    '+$m.Title) $true 16 'left')+'</w:tc></w:tr>'
  $pairs=@(@('Priority',$m.Priority),@('Purpose',$m.Purpose),@('Role',$m.Role))
  foreach($z in $pairs){$x+='<w:tr>'+(Tc (CellP $z[0] $false 16 'left') $w1 'FFFFFF')+(Tc (CellP $z[1] $false 16 'left') $w2 'FFFFFF')+'</w:tr>'}
  $nested='<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="7280" w:type="dxa"/><w:tblLayout w:type="fixed"/></w:tblPr><w:tblGrid><w:gridCol w:w="2050"/><w:gridCol w:w="1800"/><w:gridCol w:w="3430"/></w:tblGrid><w:tr><w:trPr><w:tblHeader/></w:trPr>'+(Tc (CellP 'Field / Button / Table Column' $true 15 'center') 2050 $blue)+(Tc (CellP 'Field type' $true 15 'center') 1800 $blue)+(Tc (CellP 'Functional description' $true 15 'center') 3430 $blue)+'</w:tr>'
  foreach($i in $m.Inputs){$nested+='<w:tr>'+(Tc (CellP $i[0] $false 15 'left') 2050)+(Tc (CellP $i[1] $false 15 'left') 1800)+(Tc (CellP $i[2] $false 15 'left') 3430)+'</w:tr>'};$nested+='</w:tbl>'
  $x+='<w:tr>'+(Tc (CellP 'Input' $false 16 'left') $w1)+(Tc $nested $w2)+'</w:tr>'
  foreach($z in @(@('Operations',$m.Operations),@('Use case',$m.UseCase),@('Output',$m.Output),@('DS ID',$m.DS),@('URS ID',$m.URS),@('Business Rules',$m.Rules))){$x+='<w:tr>'+(Tc (CellP $z[0] $false 16 'left') $w1)+(Tc (CellP $z[1] $false 16 'left') $w2)+'</w:tr>'}
  return $x+'</w:tbl>'+(P '' 'Normal' 'left' 18 $false 0 80)
}
function TocField(){
  $cached=(P '1. Introduction' 'TOC1' 'left' 18 $false 0 20)+(P '2. Overall Description / Overall Design' 'TOC1' 'left' 18 $false 0 20)+(P '3. Functional Specification / Detailed Design Specification' 'TOC1' 'left' 18 $false 0 20)+(P '4. Non-Functional Specification' 'TOC1' 'left' 18 $false 0 20)
  return '<w:p><w:r><w:fldChar w:fldCharType="begin" w:dirty="true"/></w:r><w:r><w:instrText xml:space="preserve"> TOC \o "1-2" \h \z \u </w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r></w:p>'+$cached+'<w:p><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p>'
}
function ImageXml([string]$rid,[string]$path,[double]$widthPt,[string]$caption){
  $im=[Drawing.Image]::FromFile($path);try{$heightPt=$widthPt*$im.Height/$im.Width}finally{$im.Dispose()};$cx=[long]($widthPt*12700);$cy=[long]($heightPt*12700);$script:docPr++;$id=$script:docPr
  $draw='<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:after="60"/></w:pPr><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="'+$cx+'" cy="'+$cy+'"/><wp:docPr id="'+$id+'" name="Figure '+$id+'"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="'+$id+'" name="'+(E ([IO.Path]::GetFileName($path)))+'"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="'+$rid+'"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="'+$cx+'" cy="'+$cy+'"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>'
  return $draw+(P $caption 'Caption' 'center' 16 $false 0 100 $true)
}
function LoadXml([string]$path){$x=New-Object Xml.XmlDocument;$x.PreserveWhitespace=$true;$x.Load($path);return $x}
function SaveXml($x,[string]$path){$set=New-Object Xml.XmlWriterSettings;$set.Encoding=New-Object Text.UTF8Encoding($false);$set.Indent=$false;$wr=[Xml.XmlWriter]::Create($path,$set);$x.Save($wr);$wr.Close()}
function AddImageRel($rels,[string]$rid,[string]$target){$n=$rels.CreateElement('Relationship',$relNs);$n.SetAttribute('Id',$rid);$n.SetAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/image');$n.SetAttribute('Target',$target);[void]$rels.DocumentElement.AppendChild($n)}
function Package([string]$template,[string]$output,[string]$body,[object[]]$images,[string]$oldTitle,[string]$newTitle,[string]$oldId,[string]$newId,[string]$name){
  $dir=Join-Path $work $name;[IO.Compression.ZipFile]::ExtractToDirectory($template,$dir)
  $docPath=Join-Path $dir 'word\document.xml';$dx=LoadXml $docPath;$ns=New-Object Xml.XmlNamespaceManager($dx.NameTable);$ns.AddNamespace('w',$wNs);$oldBody=$dx.SelectSingleNode('//w:body',$ns);$sect=$oldBody.SelectSingleNode('./w:sectPr',$ns).OuterXml
  $newXml='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="'+$wNs+'" xmlns:r="'+$rNs+'" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>'+$body+$sect+'</w:body></w:document>'
  [IO.File]::WriteAllText($docPath,$newXml,(New-Object Text.UTF8Encoding($false)))
  $relsPath=Join-Path $dir 'word\_rels\document.xml.rels';$rels=LoadXml $relsPath;$idx=0
  foreach($im in $images){$idx++;$rid='rId'+(9000+$idx);$fn=('phase3-{0:D2}{1}'-f$idx,[IO.Path]::GetExtension($im.Path));Copy-Item -LiteralPath $im.Path -Destination (Join-Path $dir ('word\media\'+$fn)) -Force;AddImageRel $rels $rid ('media/'+$fn)};SaveXml $rels $relsPath
  foreach($p in Get-ChildItem -LiteralPath (Join-Path $dir 'word') -File|Where-Object{$_.Name-match'^(header|footer)\d+\.xml$'}){$s=[IO.File]::ReadAllText($p.FullName);$s=$s.Replace($oldTitle,$newTitle).Replace($oldId,$newId);[IO.File]::WriteAllText($p.FullName,$s,(New-Object Text.UTF8Encoding($false)))}
  $settings=LoadXml (Join-Path $dir 'word\settings.xml');$sn=New-Object Xml.XmlNamespaceManager($settings.NameTable);$sn.AddNamespace('w',$wNs);$uf=$settings.SelectSingleNode('//w:updateFields',$sn);if(-not $uf){$uf=$settings.CreateElement('w','updateFields',$wNs);[void]$settings.DocumentElement.AppendChild($uf)};$uf.SetAttribute('val',$wNs,'true');SaveXml $settings (Join-Path $dir 'word\settings.xml')
  $zip=Join-Path $work ($name+'.zip');if(Test-Path $zip){Remove-Item $zip -Force};[IO.Compression.ZipFile]::CreateFromDirectory($dir,$zip,[IO.Compression.CompressionLevel]::Optimal,$false);Copy-Item $zip $output -Force
}

# Extract exact requirement rows from the current URS package.
$ursDir=Join-Path $work 'urs';[IO.Compression.ZipFile]::ExtractToDirectory($urs,$ursDir);$ux=LoadXml (Join-Path $ursDir 'word\document.xml');$un=New-Object Xml.XmlNamespaceManager($ux.NameTable);$un.AddNamespace('w',$wNs);$reqs=@()
foreach($tr in $ux.SelectNodes('//w:tbl/w:tr',$un)){$cells=@($tr.SelectNodes('./w:tc',$un));if($cells.Count-ge2){$id=(($cells[0].SelectNodes('.//w:t',$un)|ForEach-Object{$_.InnerText})-join'').Trim();$tx=(($cells[1].SelectNodes('.//w:t',$un)|ForEach-Object{$_.InnerText})-join' ').Trim();if($id-match'^4\.[1-4]\.\d+$'){$reqs+=[pscustomobject]@{Id=$id;Text=$tx}}}}
if($reqs.Count-ne69){throw "Expected 69 current URS requirements, found $($reqs.Count)."}; Write-Output 'Phase 3 URS requirements loaded.'

$abbr=@(,@('BAR','Batch Assembly Record'),,@('B&S','B&S Healthcare'),,@('DS','Design Specification'),,@('FS','Functional Specification'),,@('URS','User Requirement Specification'),,@('GMP','Good Manufacturing Practice'),,@('IPC','In-Process Check'),,@('MFG','Manufacturing / manufacturer'),,@('PCL','Product Check Log'),,@('QA / QC','Quality Assurance / Quality Control'),,@('QP','Qualified Person'),,@('IMP','Investigational Medicinal Product'))
$nfr=@(
 @('4.1 Audit Trail','Retain authenticated user, role, date/time, batch, stage, action, result and applicable previous/new values for controlled confirmations, signatures, count changes, corrections, printing and hand-offs.'),
 @('4.2 Availability','Provide the stages within the approved PLPI operating window. A temporary device, print or service interruption shall not create false completion.'),
 @('4.3 Capacity Limits','Support approved operational batch, box, sample, IPC row, photograph and history volumes. Final technical limits require confirmation within the approved PLPI environment.'),
 @('4.4 Performance','Provide a clear operational response for search, screen opening, validation and sign-off. Qualification shall confirm the approved targets.'),
 @('4.5 Recoverability','Retain committed signatures and audit events after recoverable interruption. Uncommitted handheld Line Clearance shall not be represented as completed.'),
 @('4.6 Security Requirements','Enforce authenticated role-based access and derive signature attribution from the authenticated identity.'),
 @('4.7 Error Handling','Identify the unmet condition, retain the current step and block duplicate or stale completion without overwriting the approved record.'),
 @('4.8 Usability','Use clear labels, visible status, readable values and action gating consistent with the approved desktop and handheld wireframes.'),
 @('4.9 Accuracy and Validity','Keep batch, product, material, quantity, box and room values associated with the selected controlled record and revalidate calculations at commit.'),
 @('4.10 User Access and Responsibilities','Limit each operational role to its assigned stage. Support access shall not provide uncontrolled operational sign-off.'),
 @('4.11 Testing and Traceability','Test every URS trace, role, positive flow, validation, cancellation, interruption, duplicate prevention, audit event, print action and hand-off.'),
 @('4.12 Controlled Documents and Training','Approve and train applicable SOPs, work instructions, BAR forms, handheld instructions, assembly checks and post-assembly controls before release.'),
 @('4.13 Support and Administration','Maintain approved users, roles, devices, printers and configuration and retain diagnostic evidence without exposing controlled operational data.')
)
function NfrBody([string]$title){$s=H1 $title;foreach($x in $nfr){$s+=H2 $x[0];$s+=P $x[1]};return $s}

# Functional Specification body.
$fs=''
$fs+=Table @('Role','Name / Function','Date','Signature') @(,@('Author','Yogeshkumar Vimalan - Business Analyst','',''),,@('Reviewer','Project Manager','',''),,@('Reviewer','Team Leader','',''),,@('Approver','Quality Assurance','','')) @(1440,4200,1500,1880)
$fs+=PB;$fs+=H1 'Revision History';$fs+=Table @('Version','Previous version','Reason for revision','Issued') @(,@('1','NA','Initial Functional Specification for PLPI BAR stages 9-12: Pre-Assembly QC, Production Controller handheld and room allocation, Assembly Room and Post-Assembly QC.','August 2026')) @(1040,1760,4720,1500)
$fs+=PB;$fs+=P 'TABLE OF CONTENTS' 'Heading1' 'center' 22 $true 0 140;$fs+=TocField;$fs+=PB
$fs+=H1 '1. Introduction';$fs+=P 'PLPI Batch Record Automation stages 9-12 extend the controlled electronic BAR workflow from Pre-Assembly QC through Production Controller handheld Line Clearance and room allocation, Assembly Room execution and Post-Assembly QC.'
$fs+=H2 '1.1 Purpose of the document';$fs+=P 'This document specifies the functional behaviour, controls, validations, outputs, audit events and stage hand-offs required by the current approved URS and final wireframes.'
$fs+=H2 '1.2 Scope';$fs+=P 'The scope comprises Stage 9 Pre-Assembly QC, Stage 10 Production Controller handheld Stock Take Out and room allocation, Stage 11 Assembly Room and Stage 12 Post-Assembly QC. Physical database structures, interfaces and infrastructure not established by project evidence remain outside this FS.'
$fs+=H2 '1.3 Abbreviations';$fs+=Table @('Term','Definition') $abbr @(1700,7320)
$fs+=H1 '2. Overall Description';$fs+=P 'An eligible batch enters Pre-Assembly QC, where materials and reference-sample preparation are confirmed. The Production Controller then uses the authorised SeUIC handheld to perform Stock Take Out, Box ID verification, Line Clearance and Assembly Room allocation. The allocated Assembly Room completes four controlled pages and hands the batch to Post-Assembly QC. Post-Assembly QC confirms finished quantities and pack details, prints the Quarantine Label and releases the signed record to Pre-QP.'
$fs+=P 'The four stages use role-controlled queues, mandatory action gates, authenticated user/date-time attribution, read-only completed records and explicit downstream hand-offs. Navigation or interruption before the final controlled action does not create completion.'
$fs+=H1 '3. Functional Specification';$fs+=P 'Each module profile follows the approved Phase 2 specification structure. Field classifications describe the Phase 3 change status and do not imply an unverified technical implementation.'
foreach($m in $modules){$fs+=H2 ($m.Code+' '+$m.Title);$fs+=ModuleTable $m}
$fs+=H2 '3.5 URS / FS / DS Traceability'; $trace=@(,@('4.1.1 - 4.1.12','FS-PA-001 to FS-PA-012','DS 3.1','Pre-Assembly QC controls and hand-off.'),,@('4.2.1 - 4.2.20','FS-PC-001 to FS-PC-020','DS 3.2','Production Controller handheld Line Clearance and room allocation.'),,@('Approved 4.3 IDs','FS-AR-001 to FS-AR-024','DS 3.3','Assembly four-page control and hand-off.'),,@('4.4.1 - 4.4.13','FS-PQ-001 to FS-PQ-013','DS 3.4','Post-Assembly verification and Pre-QP hand-off.')); $fs+=Table @('URS ID','FS ID','DS ID Ref','Function / requirement') $trace @(1600,1900,1300,4220)
$fs+=NfrBody '4. Non-Functional Specification'; Write-Output 'Functional Specification body assembled.'
Write-Output 'Packaging Functional Specification.'; Package $fsRef $fsOut $fs @() 'Functional Specification: PLPI Batch Record Automation Phase 2' 'Functional Specification: PLPI Batch Record Automation Stages 9-12' 'PLPI/BAR/FS/01/v1' 'PLPI/BAR/FS/02/v1' 'fs'

# Design Specification image map and body.
$imgs=@();$rmap=@{};$allPaths=@(
 Join-Path $shots '01-pre-assembly-queue.png';Join-Path $shots '01-pre-assembly-detail.png';Join-Path $shots '02-handheld-menu.png';Join-Path $shots '02-handheld-stock-take-out.png';Join-Path $shots '02-handheld-box-verification.png';Join-Path $shots '02-handheld-line-clearance.png';
 Join-Path $assembly '01-assembly-batch-queue.png';Join-Path $assembly '02-start-batch-confirmation.png';Join-Path $assembly '03-initial-checks.png';Join-Path $assembly '04-random-sample-check.png';Join-Path $assembly '05-ipc-checks.png';Join-Path $assembly '06-reconciliation-closure.png';
 Join-Path $shots '04-post-assembly-queue.png';Join-Path $shots '04-post-assembly-detail.png')
for($i=0;$i-lt$allPaths.Count;$i++){if(-not(Test-Path $allPaths[$i])){throw "Missing image $($allPaths[$i])"};$rid='rId'+(9001+$i);$imgs+=,[pscustomobject]@{Path=$allPaths[$i];Rid=$rid};$rmap[$allPaths[$i]]=$rid}
function Fig([int]$index,[string]$caption,[double]$width=430){ImageXml $rmap[$allPaths[$index-1]] $allPaths[$index-1] $width ('Figure '+$index+' - '+$caption)}
function Calls([string[]]$items){$s='';foreach($x in $items){$s+=P $x 'Normal' 'both' 18 $false 0 70};return $s}
$ds='';$ds+=P 'DESIGN SPECIFICATION' 'Heading1' 'center' 30 $true 60 80;$ds+=P 'PLPI Batch Record Automation' 'Heading2' 'center' 24 $true 0 40;$ds+=P 'Stages 9-12: Pre-Assembly QC, Production Controller Handheld, Assembly Room and Post-Assembly QC' 'Normal' 'center' 18 $false 0 120
$ds+=Table @('Role','Name / Function','Signature','Date') @(,@('Author','Yogeshkumar Vimalan - Business Analyst','To be completed during approval','To be completed'),,@('Reviewer','Project Manager','To be completed during approval','To be completed'),,@('Reviewer','Team Leader','To be completed during approval','To be completed'),,@('Approver','Quality Assurance','To be completed during approval','To be completed')) @(1400,3300,2700,1620)
$ds+=H1 'Revision History';$ds+=Table @('Version','Previous version','Reason for revision','Issued') @(,@('1','NA','Initial Design Specification for PLPI BAR stages 9-12.','August 2026')) @(1040,1760,4720,1500)
$ds+=PB;$ds+=P 'TABLE OF CONTENTS' 'Heading1' 'center' 22 $true 0 140;$ds+=TocField;$ds+=PB
$ds+=H1 '1. Introduction';$ds+=P 'This Design Specification defines the logical screen, control, state, validation, record, audit and hand-off design for PLPI BAR stages 9-12. The design is based on the current URS, current wireframes and the approved FS.'
$ds+=H2 '1.1 Purpose of the Document';$ds+=P 'The purpose is to provide an implementation-ready logical design without inventing physical database tables, API endpoints, network architecture, device-management technology or other technical components not established by project evidence.'
$ds+=H2 '1.2 Scope';$ds+=P 'The design covers the four role-controlled modules, their queues and screens, the SeUIC handheld workflow, the four Assembly pages, Post-Assembly quantity and label controls, audit attribution, completion locking and downstream status hand-offs.'
$ds+=H2 '1.3 Reference Documents';$ds+=Table @('Reference','Use') @(,@('Current Phase 3 URS','Approved user requirements and numbering.'),,@('Current stages 9-12 wireframes','Visible screen labels, controls and interaction behaviour.'),,@('Approved Phase 3 FS','Functional behaviour and traceability.'),,@('Phase 2 FS and DS','Visual and document-structure reference only; no Phase 2 process content is used.')) @(2900,6120)
$ds+=H2 '1.4 Abbreviations';$ds+=Table @('Abbreviation','Definition') $abbr @(2100,6920)
$ds+=H1 '2. Overall Design';$ds+=H2 '2.1 End-to-End Workflow';$ds+=Table @('Sequence','Stage','Design outcome') @(,@('9','Pre-Assembly QC','Signed material/reference verification and prepared assembly reference sample.'),,@('10','Production Controller Handheld','Verified stock/box, signed Line Clearance and allocated Assembly Room.'),,@('11','Assembly Room','Four signed controlled pages and completed reconciliation.'),,@('12','Post-Assembly QC','Verified finished packs, controlled box allocation, Quarantine Label and Pre-QP hand-off.')) @(1100,2900,5020)
$ds+=H2 '2.2 Status and Route Logic';$ds+=Table @('State','Permitted design behaviour') @(,@('Available','Display only to the authorised role after the preceding stage has completed.'),,@('In Progress','Permit entry and navigation while retaining only committed controlled events.'),,@('Ready for Sign-off','Enable completion only after all applicable gates pass.'),,@('Completed','Show attribution read-only, prevent ordinary overwrite and publish the next-stage status.'),,@('Cancelled / interrupted','Remain at the last committed non-completed state and do not create completion.')) @(2400,6620)
$ds+=H2 '2.3 Roles and Access';$ds+=Table @('Role','Permitted module') @(,@('Pre-Assembly QC User','Stage 9 queue, verification, reference-sample controls and sign-off.'),,@('Production Controller','Stage 10 SeUIC handheld Stock Take Out, Line Clearance and room allocation.'),,@('Assembly Room User','Stage 11 allocated-room queue and four controlled Assembly pages.'),,@('Post-Assembly QC User','Stage 12 finished-pack verification, box allocation, Quarantine Label and sign-off.'),,@('Support / Administration','Approved configuration and support only; no uncontrolled operational signature.')) @(2900,6120)
$ds+=H2 '2.4 Common Design Principles';foreach($x in @('Role access and transaction validation are authoritative; display gating is not the sole security control.','Every controlled signature records authenticated user, role, batch, action and date/time.','Completed stage and page records are read-only in the ordinary workflow; corrections use the approved amendment route.','Physical persistence, interface, identity, device and printer implementation remain technical confirmation items where not evidenced.')){$ds+=Bullet $x}
$ds+=H1 '3. Detailed Design Specification'
$ds+=H2 '3.1 Pre-Assembly QC Module';$ds+=Fig 1 'Pre-Assembly QC batch queue';$ds+=Calls @('Callout 1 - Search criteria. B&S Batch Number and MFG Lot No. filter the Stage 9 eligible population.','Callout 2 - Queue rows. Product, batch, route and status remain read-only and selection opens the controlled Stage 9 record.','Callout 3 - Completed history. A signed record remains read-only and cannot be signed again.')
$ds+=Fig 2 'Pre-Assembly verification, reference-sample controls and sign-off';$ds+=Calls @('Callout 1 - Product and route context. Values populate from the selected batch and remain read-only.','Callout 2 - Printed-material checklist. Every displayed Type Of label and Reference code row requires Checked & Confirmed.','Callout 3 - Counts. No of specimen, No Of Leaflet Folds and Tamper seal per pack accept non-negative whole values.','Callout 4 - MARKS. If changed from the original, Reason becomes enabled and mandatory.','Callout 5 - Mockup. Opens the approved presentation used to prepare and compare the assembly reference sample.','Callout 6 - User Sign Off. Enabled only after all displayed checks, counts, conditional reason and route amendments are complete.')
$ds+=P 'Detailed design sequence:';foreach($x in @('Step 1 - Search and open an eligible Stage 9 batch.','Step 2 - Populate product, route, reference and original MARKS values.','Step 3 - Record each material confirmation and the three controlled counts.','Step 4 - Require Reason for a MARKS change and both route-amendment initials when applicable.','Step 5 - Open the Mockup and prepare/compare the assembly reference sample.','Step 6 - User Sign Off revalidates gates, records user/date-time, locks the record and publishes the batch to Production Control.')){$ds+=P $x};$ds+=P 'Validation and error handling: Missing material checks, counts, change reason or applicable amendment initials keep sign-off disabled. Back or interruption leaves the batch unsigned. Entry: Stage 9 eligible batch. Exit: signed Pre-Assembly record. URS 4.1.1-4.1.12; FS 3.1.'
$ds+=H2 '3.2 Production Controller Handheld / Room Allocation Module';$ds+=Fig 3 'SeUIC GOODS IN menu used by the Production Controller' 190;$ds+=Calls @('Callout 1 - STOCK TAKE OUT is the Stage 10 entry point. Other menu tiles are visible context but are not Stage 10 functions.')
$ds+=Fig 4 'Stock Take Out details and TRANSFER action' 190;$ds+=Calls @('Callout 1 - Stock ID accepts scanner or manual entry and identifies the stock record.','Callout 2 - Product, Part No., Batch No., Goods In Boxes, Qty., Location, IMP and Contract populate read-only.','Callout 3 - TRANSFER opens Box ID verification for the displayed stock record.')
$ds+=Fig 5 'Scan Box ID for Verification dialog' 190;$ds+=Calls @('Callout 1 - Box ID is mandatory; blank CONFIRM displays validation and does not advance.','Callout 2 - CONFIRM validates and opens a new Line Clearance; CANCEL closes without completion.')
$ds+=Fig 6 'Handheld Line Clearance and Assembly Room allocation' 190;$ds+=Calls @('Callout 1 - Product-label check confirms product name, expiry date and lot size on the box label.','Callout 2 - Number of boxes accepts a positive whole number. A change opens old/new confirmation; Cancel restores the prior value.','Callout 3 - Assign Assembly Room requires Room1 or Room2.','Callout 4 - CONFIRMED BY is gated by both checks, count, change decision and room. Confirmation updates the BAR and displays BAR UPDATED, user, date/time and room.')
$ds+=P 'Detailed handheld sequence:';foreach($x in @('Step 1 - Open GOODS IN and select STOCK TAKE OUT.','Step 2 - Scan or enter Stock ID and review its read-only details.','Step 3 - Select TRANSFER, scan/enter Box ID and CONFIRM; Cancel or blank input does not complete.','Step 4 - Complete both Line Clearance checks and confirm the positive whole-number box count.','Step 5 - Explicitly Confirm a changed count or Cancel to restore the prior value.','Step 6 - Select Room1 or Room2 and use CONFIRMED BY; commit the BAR update once and lock the form.','Step 7 - Start every later transfer with a new blank Line Clearance; keep the prior signed form only in history.')){$ds+=P $x};$ds+=P 'Logical committed fields: Stock ID, Box ID verification result, batch, product, confirmed boxes, room, both check results, authenticated user and date/time. Physical BAR interface and handheld connectivity remain technical confirmation items. Entry: Stage 9 complete. Exit: signed Line Clearance and room allocation. URS 4.2.1-4.2.20; FS 3.2.'
$ds+=H2 '3.3 Assembly Room Module';$ainfo=@(
 @('Assembly Room batch queue and room-controlled work list','Queue displays only batches allocated to the room; search, refresh, active/completed state and check-in/out are controlled.'),@('Assembly start confirmation','Opening an unstarted batch requires confirmation and records Assembly Started By and date/time.'),@('Initial Checks controlled page','Mandatory setup and material confirmations gate signature; a signed page becomes read-only.'),@('Random Sample Check controlled page','Required observations remain associated with each applicable box and gate page signature.'),@('IPC Checks and supporting evidence','Scheduled/minimum rows are provided, additional rows may be added and required photo evidence remains associated with the IPC event.'),@('Reconciliation and Closure controlled page','Issued, used, damaged, surplus and leftover values are validated before the final page signature and hand-off.'))
for($i=0;$i-lt6;$i++){$ds+=Fig (7+$i) $ainfo[$i][0];$ds+=P ('Callout - '+$ainfo[$i][1])}
$ds+=P 'Detailed Assembly sequence:';foreach($x in @('Step 1 - Open an allocated active batch and confirm start.','Step 2 - Complete and sign Initial Checks.','Step 3 - Complete Random Sample Check for every applicable box and sign the page.','Step 4 - Complete required IPC rows, additional checks and photo evidence and sign the page.','Step 5 - Complete Reconciliation & Closure and sign the page.','Step 6 - After all four page signatures exist, final completion records finish user/date-time, locks the pages and publishes the batch to Post-Assembly QC.')){$ds+=P $x};$ds+=P 'A page cannot sign with missing mandatory data. Break, Back or interruption retains committed page signatures but does not create final completion. Entry: confirmed room allocation. Exit: four signed pages and Post-Assembly QC availability. URS: approved 4.3 requirements; FS 3.3.'
$ds+=H2 '3.4 Post-Assembly QC Module';$ds+=Fig 13 'Post-Assembly QC active and completed batch queue';$ds+=Calls @('Callout 1 - BNS Batch No. and MFG Lot No. filter only assembly-complete Stage 12 batches.','Callout 2 - Active opens for controlled completion; Completed remains read-only and cannot be signed again.')
$ds+=Fig 14 'Production Checking quantities, BAR comparison, label actions and sign-off';$ds+=Calls @('Callout 1 - Total Packs, Total Boxes and No. of Packs Checked require positive whole numbers.','Callout 2 - When Total Boxes exceeds one, every box quantity is mandatory and the sum must equal Total Packs.','Callout 3 - Every Pack Details Against BAR row and expiry confirmation is mandatory.','Callout 4 - Print Quarantine Label is associated with the selected batch; Test Print does not complete Stage 12.','Callout 5 - User Sign Off revalidates all gates, records Signed By/Signed At, marks Completed and publishes to Pre-QP.')
$ds+=P 'Detailed Post-Assembly sequence:';foreach($x in @('Step 1 - Search and open an assembly-complete batch.','Step 2 - Record Total Packs, Total Boxes and No. of Packs Checked.','Step 3 - When required, enter every box quantity and confirm only when the total matches Total Packs.','Step 4 - Confirm every Pack Details Against BAR row and record comments where required.','Step 5 - Print the Quarantine Label and display the result.','Step 6 - User Sign Off records user/date-time and releases the immutable completed record to Pre-QP.')){$ds+=P $x};$ds+=P 'Invalid quantities, box-total mismatch, unchecked BAR rows or stale completion prevent sign-off. Print failure is not shown as success. Entry: Assembly complete. Exit: signed Stage 12 available to Pre-QP. URS 4.4.1-4.4.13; FS 3.4.'
$ds+=H2 '3.5 Workflow Status, Corrections and Audit Behaviour';$ds+=Table @('Design control','Required behaviour') @(,@('Queue eligibility','Revalidate preceding-stage completion and role before display or commit.'),,@('Signature transaction','Revalidate gates, prevent duplicate completion, commit data/audit, lock the record and publish the next stage as one controlled outcome.'),,@('Correction','Use the approved amendment route with reason, prior/new value, user and date/time; never overwrite the original event.'),,@('Interruption','Retain committed signatures, discard uncommitted completion and return a clear recoverable state.'),,@('Printing','Associate BAR and Quarantine Label output with the selected batch; failed/cancelled output does not record success.'),,@('Open technical decisions','Physical persistence, identity integration, SeUIC connectivity/offline policy, BAR interface, printer configuration and IPC photo storage require approved technical confirmation.')) @(2900,6120)
$ds+=NfrBody '4. Additional Non-Functional Requirements'; Write-Output 'Design Specification body assembled.'
Package $dsRef $dsOut $ds $imgs 'Design Specification: PLPI Batch Record Automation Phase 2' 'Design Specification: PLPI Batch Record Automation Stages 9-12' 'PLPI/BAR/DS/01/v1' 'PLPI/BAR/DS/02/v1' 'ds'
Write-Output "Created $fsOut";Write-Output "Created $dsOut";Write-Output "Requirements traced: $($reqs.Count)"
